########################################
#~ définitions
########################################

# Executables à générer
BIN=bin/client  bin/server  bin/anneau

# liste des fichiers sources 
SRCS0=client.c
SRCS1=server.c
SRCS2=anneau.c
#SRCS3=node.c

default: $(BIN)

########################################
#~ regles pour l'executable
########################################

obj/%.o: %.c
	gcc -Wall -Iinclude -c $< -o $@

bin/client: $(SRCS0:%.c=obj/%.o)
	gcc -o $@ $+

bin/server: $(SRCS1:%.c=obj/%.o)
	gcc -o $@ $+

bin/anneau: $(SRCS2:%.c=obj/%.o)
	gcc -o $@ $+

#bin/node: $(SRCS3:%.c=obj/%.o)
#	gcc -o $@ $+

clean:
	rm -f $(BIN) obj/*.o *~
